In [1]:
import numpy as np

In [5]:
A = np.array([[4,2], [4, -1]])
b = np.array([[8], [5]])
np.dot(np.linalg.inv(A), b)

array([[1.5],
       [1. ]])

In [9]:
A = np.array([[4,2,2], [3,2,1], [-2,-1,-2]])
np.dot(np.linalg.inv(A), np.array([[5], [7], [-3]]))

array([[-2.5],
       [ 7. ],
       [ 0.5]])

In [15]:
T = np.array([[1,0], [-1,1]])
A = np.array([[2,1], [2, -1]])
np.linalg.inv(T)
#

array([[1., 0.],
       [1., 1.]])

In [20]:
A = np.array([[1,0,2], [2,-1,0], [0,1,0]])
B = np.array([[0, 2, 1, 3], [-1, 0, 6, 4], [1, 0, 1, -7], [0, 7, 0, 1]])
C = np.array([[1, 2, 1, 2]])
D = np.array([[1, -1], [0, 1], [-1, 0]])
np.dot(np.dot(np.transpose(C), C), B)

array([[-1, 16, 14,  6],
       [-2, 32, 28, 12],
       [-1, 16, 14,  6],
       [-2, 32, 28, 12]])

In [22]:
!pip install C:\Users\Home\Documents\наде\sympy-1.11.1-py3-none-any.whl

Processing c:\users\home\documents\наде\sympy-1.11.1-py3-none-any.whl
sympy is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.


In [23]:
from sympy import Matrix
A = np.array([[0, 1, 0, 1], [1,1, 1, 1], [2, 3, 4, 5], [5, 7, 9, 11]])
Matrix(A).jordan_form()

Exception ignored in: <generator object iter_fields at 0x000001E0AD8031B0>
Traceback (most recent call last):
  File "C:\Users\Home\miniconda3\envs\py-scripts\lib\ast.py", line 254, in iter_fields
    yield field, getattr(node, field)
KeyboardInterrupt: 


KeyboardInterrupt: 

In [53]:
B = np.array([[1,3,1,0], [1, 0, -1, 2], [0, 0, 1,2]])
C = np.array([[1, 2, 3, -1]])
# inv = np.linalg.inv(A)
# inv
np.dot(np.dot(np.dot(C.transpose(), C), B.transpose()), B)

array([[  6,  30,  15,  -6],
       [ 12,  60,  30, -12],
       [ 18,  90,  45, -18],
       [ -6, -30, -15,   6]])

In [37]:
A = np.array([[0, 2, -3], [2, 1, 0], [1, 1, 1]])
B = np.array([[4, 1, -2], [2, 0, 0], [-4, 0, -1]])
C = np.array([[3, 1, -2], [1, 1, 4]])
D = np.array([[2, -1], [0, -5], [-1, 0]])
np.sum(np.dot(np.dot(C, A+B), D))

-42

In [49]:
np.array([])

array([], dtype=float64)

In [58]:
from scipy.linalg import lu
P, L, U = lu(np.array([[-3, 4, 0], [1, -3, 2], [-6, 7, 1]]))
L

array([[ 1.        ,  0.        ,  0.        ],
       [-0.16666667,  1.        ,  0.        ],
       [ 0.5       , -0.27272727,  1.        ]])

In [9]:
import numpy as np
A = np.array([[0, 2], [-1, 1]])
X = [[3], [4]]
np.dot(np.dot(np.dot(A, np.linalg.inv(np.dot(A.transpose(), A))), A.transpose()), X)

array([[3.],
       [4.]])

In [14]:
A = np.array([[1, 2, 1], [1, 0, 3], [2, 0, 4], [1, -1, 2]])
b = np.array([8, -2, 0, 16])
first = np.linalg.inv(np.dot(A.transpose(), A))
second = np.dot(first, A.transpose())
third = np.dot(second, b)
third

array([23. , -4.6, -9.6])

In [19]:
from scipy.linalg import lu
P, L, U = lu(np.array([[7, 1, 2], [5, 5, -2], [3, 3, 6], [1, 7, 2]]))
print(P)
print(L)
print(U)
print(np.dot(P, L))

[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
[[ 1.          0.          0.        ]
 [ 0.14285714  1.          0.        ]
 [ 0.42857143  0.375       1.        ]
 [ 0.71428571  0.625      -1.        ]]
[[7.         1.         2.        ]
 [0.         6.85714286 1.71428571]
 [0.         0.         4.5       ]]
[[ 1.          0.          0.        ]
 [ 0.71428571  0.625      -1.        ]
 [ 0.42857143  0.375       1.        ]
 [ 0.14285714  1.          0.        ]]


In [3]:
E_1 = np.array([[-2, 1], [1, -1]])
E_2  = np.array([[-1, 2], [2, 1]])
T = np.dot(np.linalg.inv(E_1), E_2)
A = np.array([[5, -3], [2, -2]])
inv = np.dot(np.linalg.inv(T), A)
np.dot(inv, T)

array([[ 0.8, -3.6],
       [-1.6,  2.2]])

In [9]:
A = np.array([[3, -2], [4, -5]])
T = np.array([[1,4], [2, 1]])
inv = np.dot(np.linalg.inv(T), A)
np.dot(inv, T)
np.linalg.eig(A)

(array([ 1.82842712, -3.82842712]),
 array([[0.86285621, 0.28108464],
        [0.50544947, 0.95968298]]))