In [1]:
import numpy as np

In [2]:
#1
A = np.array([[3000, 150], [-100, 5]])
np.linalg.det(A)

29999.999999999956

In [3]:
A = np.array([[-1,3,1], [-2,2,0], [0,3,1]])
np.linalg.det(A)

-2.0

In [18]:
A = np.array([[2,3,3], [-2,1,2], [2,0,-1]])
np.linalg.eigvals(A)

array([ 2., -1.,  1.])

In [23]:
A = np.array([[1,-3,1], [-5,0,4], [-7,-5,1]])
T = np.array([[1,3,2], [0,1,-2], [1,4,-1]])
inv = np.dot(np.linalg.inv(T), A)
np.dot(inv, T)

array([[ -51., -215.,   65.],
       [  13.,   55.,  -18.],
       [   7.,   27.,   -2.]])

In [24]:
#Week 4
#4
A = np.array([[-4,6], [-3,5]])
np.linalg.eigvals(A)

array([-1.,  2.])

In [28]:
#6
A = np.array([[1,0,1], [-2,1,4], [6,-3,8]])
np.linalg.eigvals(A)
np.linalg.det(A)

19.999999999999996

In [30]:
#10
A = np.array([[4,4,0], [-2,-2,0], [2,4,2]])
np.linalg.eigvals(A)

array([2., 0., 2.])

In [34]:
A = np.array([[0,2], [-3,5]])
np.linalg.eigvals(A)
T = np.array([[1,-3], [-1, 2]])
np.linalg.inv(T)

array([[-2., -3.],
       [-1., -1.]])

In [35]:
#7
A = np.array([[2,1,0], [-1,0,1], [1,3,1]])
np.linalg.eigvals(A)

array([-1.        ,  1.99999998,  2.00000002])

In [52]:
# experiments
A = np.array([[1,2,3,5], [5,2,7,8], [9,1,11,12], [15,14,15,16]])
A = A.transpose()
B = np.array([-A[0] + 2 * A[1], 2 * A[0] - 3 * A[1] - A[2], A[0] + 2 * A[1] - A[2] + 2 * A[3], -A[0] + A[1] + A[2] + A[3]])
B_2 = np.array([-A[0] + 2 * A[1], 2 * A[0] - 3 * A[1] - 3 * A[2], A[0] + 2 * A[1] - A[2] + 2 * A[3], -A[0] + A[1] + A[2] + A[3]])
y = np.array([[3,-1], [5,0]])
T = np.array([[1,1,-1,1], [2,3,1,2], [0,1,1,3], [0,0,2,-1]])
np.linalg.det(T)

-4.0